-- generated by scripts/seed-reference.mjs — do not edit by hand
-- source: supabase/seed/exercises.draft.json
insert into exercises (id, name, aliases, met, unit, is_ambulatory)
values
  ('ex_walk', 'Walking', array['walk', 'walking', 'sair', 'tehelna', 'chalna', 'paidal', 'stroll', 'morning walk']::text[], 3.8, 'minutes', true),
  ('ex_brisk_walk', 'Brisk Walking', array['brisk walk', 'brisk walking', 'fast walk', 'power walk', 'tez chalna', 'speed walk']::text[], 4.8, 'minutes', true),
  ('ex_jog', 'Jogging', array['jog', 'jogging', 'jogged', 'light run', 'slow run']::text[], 7.5, 'minutes', true),
  ('ex_run', 'Running', array['run', 'running', 'ran', 'daud', 'daudna', 'bhaag', 'bhaagna', 'went for a run']::text[], 9.3, 'minutes', true),
  ('ex_treadmill', 'Treadmill', array['treadmill', 'treadmill run', 'treadmill walk', 'running machine']::text[], 6, 'minutes', true),
  ('ex_hike', 'Hiking', array['hike', 'hiking', 'trek', 'trekking', 'trail walk', 'hill climb']::text[], 6, 'minutes', true),
  ('ex_cycling', 'Cycling', array['cycling', 'cycle', 'cycled', 'bike ride', 'biking', 'bicycle', 'cardio bike', 'spin', 'spinning', 'saikal']::text[], 7, 'minutes', false),
  ('ex_swimming', 'Swimming', array['swim', 'swimming', 'swam', 'laps', 'pool', 'tairna', 'tairaki']::text[], 6, 'minutes', false),
  ('ex_yoga', 'Yoga', array['yoga', 'yog', 'hatha yoga', 'yoga class', 'asana', 'asanas']::text[], 2.7, 'minutes', false),
  ('ex_surya_namaskar', 'Surya Namaskar', array['surya namaskar', 'suryanamaskar', 'sun salutation', 'sun salutations', 'surya namaskaar']::text[], 2.7, 'minutes', false),
  ('ex_gym_weights', 'Gym / Weight Training', array['gym', 'weight training', 'weights', 'weight lifting', 'lifting', 'workout', 'strength training', 'resistance training', 'gym workout', 'gym session']::text[], 4, 'minutes', false),
  ('ex_badminton', 'Badminton', array['badminton', 'badminton game', 'shuttle', 'shuttlecock', 'played badminton']::text[], 5.5, 'minutes', false),
  ('ex_cricket', 'Cricket', array['cricket', 'played cricket', 'cricket khela', 'gully cricket', 'batting', 'bowling']::text[], 4.8, 'minutes', false),
  ('ex_football', 'Football', array['football', 'soccer', 'played football', 'footy', 'football match', '5-a-side']::text[], 7, 'minutes', false),
  ('ex_skipping', 'Skipping Rope', array['skipping', 'skipping rope', 'jump rope', 'rope skipping', 'rassi kudna', 'skips']::text[], 11.8, 'minutes', false),
  ('ex_dancing', 'Dancing', array['dancing', 'dance', 'danced', 'dance practice', 'garba', 'bhangra', 'naach', 'naachna']::text[], 5, 'minutes', false),
  ('ex_stairs', 'Stairs Climbing', array['stairs', 'stair climbing', 'climbing stairs', 'stairs climbing', 'step climbing', 'seedhi chadna', 'seedhiyan']::text[], 8, 'minutes', false),
  ('ex_elliptical', 'Elliptical Trainer', array['elliptical', 'cross trainer', 'elliptical trainer', 'cross-trainer', 'crosstrainer']::text[], 5, 'minutes', false),
  ('ex_zumba', 'Zumba', array['zumba', 'zumba class', 'aerobics', 'aerobic dance', 'dance workout', 'cardio dance']::text[], 6.5, 'minutes', false),
  ('ex_pilates', 'Pilates', array['pilates', 'pilate', 'reformer pilates', 'mat pilates']::text[], 3, 'minutes', false)
on conflict (id) do update set name = excluded.name, aliases = excluded.aliases, met = excluded.met, unit = excluded.unit, is_ambulatory = excluded.is_ambulatory;
