// Pure parsing/validation for the IFCT 2017 import (spec/06 layer 1).
// No I/O here — ifct-import.mjs does the reading and writing.

/**
 * IFCT 2017 column names → ingredients schema. Best-guess defaults from the
 * published table's nomenclature; override with --mapping when the real file
 * arrives if its headers differ.
 */
export const DEFAULT_MAPPING = {
  id: 'code',
  name: 'name',
  name_hi: 'name_hi',
  kcal_100g: 'enerc_kcal',
  protein_100g: 'protcnt_g',
  carbs_100g: 'choavldf_g',
  fat_100g: 'fatce_g',
  fiber_100g: 'fibtg_g',
  sugar_100g: 'fsugar_g',
};

/** Minimal RFC-4180 CSV: quoted fields, escaped quotes, CRLF. Header row required. */
export function parseCsv(text) {
  const rows = [];
  let field = '';
  let record = [];
  let inQuotes = false;
  const pushField = () => {
    record.push(field);
    field = '';
  };
  const pushRecord = () => {
    if (record.length > 1 || (record[0] ?? '') !== '') rows.push(record);
    record = [];
  };
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += c;
      }
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ',') {
      pushField();
    } else if (c === '\n') {
      pushField();
      pushRecord();
    } else if (c !== '\r') {
      field += c;
    }
  }
  if (field !== '' || record.length > 0) {
    pushField();
    pushRecord();
  }
  const header = rows.shift();
  if (!header) return [];
  return rows.map((r) => Object.fromEntries(header.map((h, i) => [h.trim(), r[i] ?? ''])));
}

function num(value, { required, field, row }) {
  const trimmed = (value ?? '').trim();
  if (trimmed === '') {
    if (required) throw new Error(`row ${row}: missing required numeric field ${field}`);
    return null;
  }
  const n = Number(trimmed);
  if (!Number.isFinite(n)) throw new Error(`row ${row}: ${field} is not a number: "${trimmed}"`);
  return n;
}

/** Map raw CSV records to ingredients rows, refusing garbage rather than importing it. */
export function toIngredientRows(records, mapping) {
  return records.map((rec, i) => {
    const row = i + 2; // header is line 1
    const code = (rec[mapping.id] ?? '').trim();
    const name = (rec[mapping.name] ?? '').trim();
    if (!code) throw new Error(`row ${row}: missing IFCT code (column "${mapping.id}")`);
    if (!name) throw new Error(`row ${row}: missing name`);
    const kcal = num(rec[mapping.kcal_100g], { required: true, field: 'kcal', row });
    // densest real food is pure fat at ~900 kcal/100g; past that it's a parse error
    if (kcal < 0 || kcal > 950) throw new Error(`row ${row}: kcal out of range: ${kcal}`);
    const nameHi = (rec[mapping.name_hi] ?? '').trim();
    return {
      id: `IFCT_${code}`,
      name,
      name_hi: nameHi === '' ? null : nameHi,
      kcal_100g: kcal,
      protein_100g: num(rec[mapping.protein_100g], { required: true, field: 'protein', row }),
      carbs_100g: num(rec[mapping.carbs_100g], { required: true, field: 'carbs', row }),
      fat_100g: num(rec[mapping.fat_100g], { required: true, field: 'fat', row }),
      fiber_100g: num(rec[mapping.fiber_100g], { required: false, field: 'fiber', row }),
      sugar_100g: num(rec[mapping.sugar_100g], { required: false, field: 'sugar', row }),
    };
  });
}

function sqlLit(value) {
  if (value === null) return 'null';
  if (typeof value === 'number') return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

/** Idempotent seed SQL: re-running an import updates rather than duplicates. */
export function toSql(rows) {
  const cols = [
    'id',
    'name',
    'name_hi',
    'kcal_100g',
    'protein_100g',
    'carbs_100g',
    'fat_100g',
    'fiber_100g',
    'sugar_100g',
  ];
  const values = rows.map((r) => `  (${cols.map((c) => sqlLit(r[c])).join(', ')})`).join(',\n');
  const updates = cols
    .filter((c) => c !== 'id')
    .map((c) => `${c} = excluded.${c}`)
    .join(', ');
  return (
    `-- generated by scripts/ifct-import.mjs — do not edit by hand\n` +
    `insert into ingredients (${cols.join(', ')})\nvalues\n${values}\n` +
    `on conflict (id) do update set ${updates};\n`
  );
}

/**
 * Every dish ingredient ref must map (via refMap) to an ingredient id that
 * exists in the imported set. Returns the sorted list of refs that don't.
 */
export function validateDishRefs(dishes, refMap, knownIngredientIds) {
  const missing = new Set();
  for (const dish of dishes) {
    for (const di of dish.ingredients) {
      const mapped = refMap[di.ref];
      if (!mapped || !knownIngredientIds.has(mapped)) missing.add(di.ref);
    }
  }
  return [...missing].sort();
}
